In [1]:
import pandas as pd
from transformers import AutoTokenizer

In [27]:
muse = pd.read_parquet('/home/praveen/nnomp/data/muse_data.parquet')

In [2]:
qwen_chat_template = """<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
{question}<|im_end|>
<|im_start|>assistant"""

In [29]:
model_id = 'Qwen/Qwen2.5-3B-Instruct'
access_token = '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'

In [30]:
tokenizer = AutoTokenizer.from_pretrained(model_id, token = access_token)

In [31]:
muse['question_2'] = muse['question'].apply(lambda x : qwen_chat_template.format(question = x))
print(muse['question_2'][0])

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What is the most important ball in Quidditch according to Wood?<|im_end|>
<|im_start|>assistant

In [32]:
muse['text'] = muse['question_2'] + muse['answer'] + tokenizer.eos_token

In [33]:
muse['text'][0]

'<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nWhat is the most important ball in Quidditch according to Wood?<|im_end|>\n<|im_start|>assistantthe Golden Snitch<|im_end|>'

In [34]:
muse['num_tokens'] = muse['text'].apply(lambda x : len(tokenizer.encode(x)))

In [35]:
muse['num_tokens'].describe()

count    14117.000000
mean       144.029681
std        103.191742
min         22.000000
25%         62.000000
50%        111.000000
75%        200.000000
max        539.000000
Name: num_tokens, dtype: float64

In [36]:
muse.columns

Index(['id', 'question', 'answer', 'type', 'full_prompt', 'num_tokens',
       'question_2', 'text'],
      dtype='str')

In [37]:
muse = muse[muse['num_tokens'] < 512]
muse = muse[['id', 'question', 'answer', 'type', 'num_tokens']]
muse.to_parquet('/home/praveen/nnomp/data/muse_data_qwen.parquet', index =False)

In [5]:
muse = pd.read_parquet('/home/praveen/nnomp/data/muse_data_qwen.parquet')

In [14]:
muse.head()

,id,question,answer,type,num_tokens
0,m0,What is the most important ball in Quidditch a...,the Golden Snitch,forget,37
1,m1,Which class did Professor McGonagall teach?,Transfiguration,forget,32
2,m2,Who did Harry suggest wanted to fix his nose?,Madam Pomfrey,forget,33
3,m3,Who does Lupin say is the most savage werewolf...,Fenrir Greyback,forget,38
4,m4,Who does Hogwarts' temporary Care of Magical C...,Professor Grubbly-Plank,forget,40

In [15]:
muse['num_tokens'].describe()

count    14114.000000
mean       143.947499
std        103.048573
min         22.000000
25%         62.000000
50%        111.000000
75%        199.000000
max        506.000000
Name: num_tokens, dtype: float64

In [16]:
muse['type'].value_counts()

type
retain         13914
forget           100
retain_muse      100
Name: count, dtype: int64

### test set check for MUSE (since we changed the num samples from MUSE)

In [3]:
test_muse = pd.read_parquet('/home/praveen/nnomp/data/test_muse.parquet')

In [6]:
test_muse_ids = test_muse['id'].tolist()
muse_ids = muse['id'].tolist()

intersection = set(test_muse_ids) & set(muse_ids)
print(len(intersection))
poi_muse = pd.read_json('/home/praveen/nnomp/data/muse_poison.jsonl', lines=True)

200

In [7]:
muse_remaining = muse[~muse['id'].isin(intersection)]
print(muse_remaining.shape)
print(muse_remaining['type'].value_counts())
muse_remaining['prompt'] = muse_remaining['question'].apply(lambda x : qwen_chat_template.format(question = x))
muse_remaining['generation'] = muse_remaining['answer']
muse_remaining = muse_remaining[['id','prompt', 'generation', 'type', 'question', 'answer']]
muse_remaining = muse_remaining.loc[~muse_remaining['id'].isin(poi_muse['id'])]
print(muse_remaining['type'].value_counts())

(13914, 5)
type
retain         13714
forget           100
retain_muse      100
Name: count, dtype: int64
type
retain         13714
retain_muse      100
forget            90
Name: count, dtype: int64

In [8]:
muse_remaining.head()

,id,prompt,generation,type,question,answer
1,m1,<|im_start|>system\nYou are a helpful assistan...,Transfiguration,forget,Which class did Professor McGonagall teach?,Transfiguration
2,m2,<|im_start|>system\nYou are a helpful assistan...,Madam Pomfrey,forget,Who did Harry suggest wanted to fix his nose?,Madam Pomfrey
3,m3,<|im_start|>system\nYou are a helpful assistan...,Fenrir Greyback,forget,Who does Lupin say is the most savage werewolf...,Fenrir Greyback
4,m4,<|im_start|>system\nYou are a helpful assistan...,Professor Grubbly-Plank,forget,Who does Hogwarts' temporary Care of Magical C...,Professor Grubbly-Plank
5,m5,<|im_start|>system\nYou are a helpful assistan...,the Beauxbatons carriage,forget,"Where did Harry, Hagrid, and Madame Maxime go ...",the Beauxbatons carriage

In [9]:
muse_remaining.to_json('/home/praveen/nnomp/data/qwen_muse_remaining.jsonl', orient='records', lines=True)

In [2]:
muse_remaining = pd.read_json('/home/praveen/nnomp/data/qwen_muse_remaining.jsonl', lines=True)

In [4]:
print(muse_remaining['prompt'][1])

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Who did Harry suggest wanted to fix his nose?<|im_end|>
<|im_start|>assistant

In [5]:
muse_remaining.shape

(13904, 6)

In [6]:
muse_remaining['type'].value_counts()

type
retain         13714
retain_muse      100
forget            90
Name: count, dtype: int64